### ISSUE TITLE
Does markToDisplayMark() violate tell-don't-ask?

### ISSUE THREAD

**Issue by theScottyJam** [robertbraeutigam/tictactoe#3]
In ConsoleUI.java, you have this snippet of code:

```java
   private String markToDisplayMark(Cell cell) {
      if (cell.isMine()) {
            return ""+mineMark;
      } else if (cell.isEnemys()) {
            return ""+enemysMark;
      } else {
            return ".";
      }
   }
```

Doesn't this violate the tell-don't-ask principle? You're asking if the cell has your mark in it, or your opponent's mark, or if it's empty, and depending on each of these scenarios you create a different string representation of the cell. But, wouldn't it be "more OOP" to just tell the cell to make a string represenation of itself, and to get rid of the isMine/isEnemys/isEmpty methods?

(I'm personally fine with the code as-is, but I understand this repository is supposed to be showcasing principles like tell-don't-ask which is why I bring it up).

**Comment by robertbraeutigam** [comment]
You're right, it does violate tell-don't-ask.

This is one of those cases, where the trade-off weights in the other direction. We didn't yet discuss this, but there are valid reasons to hand out raw data sometimes. So data should always come with its associated behavior, right? But, what if you just don't know the associated behavior? Not just that, but you *can't* know.

This occurs frequently with libraries or with code that will be used later in ways which we can't yet tell. A good example is the Java Throwable.  For a long time there was only `printStackTrace()` to get to the actual stack trace, which was good "OO" style. But people wanted to store it in DB, prettify it, etc, so `getStackTrace()` was added so people could do whatever they wanted with it. This getter obviously violates tell-don't-ask and also LoD. But, because we can't know all the use-cases, we can't actually do it any other way.

The (imaginary) requirements for this project include extensibility for different UIs and different Players at a later time, including automated Players. So we *can't* know how things will be presented or used. Therefore, we just have to give out some data. If I would not have this requirement, the Cell would certainly have a `display()` method.

Just to reiterate, it's not just that you don't know or don't want to know the associated behavior, it's that you *can't* know.

**Comment by theScottyJam** [comment]
> But, what if you just don't know the associated behavior? Not just that, but you can't know.

Ok, this makes sense. After posting that, I had realized that it's much harder than I thought to get rid of the isWhatever() functions on the cell. Part of the reason, is that sometimes an algorithm simply needed to be aware of the raw data of both the cell's content, and other data (like, who's turn it is), e.g. when a random player is going and needs to make a random move, there's no way for them to pick a "random empty cell" without having knowledge of which cells are empty and which ones are not - this isn't behavior that can be placed into the cell class, the cell class has to expose something like an isEmpty() function.

(btw - I just stumbled upon this repo from seeing someone's comment on your blog. I don't actually know anything about who this repo was intended for, or if it was presented in some other blog post, but I did see it as an opportunity to better understand the coding style you were trying to present. I might post further questions like these)

**Comment by robertbraeutigam** [comment]
Just to be clear, if this were a single application, like "normal" projects are, not just an "engine" designed to be extended by external code, I would absolutely include the `display()` function into the `Cell` and the selection of a random empty cell into the `Board` perhaps.

There would be no `isEmpty()`, nor would the `Cell` need to expose other raw information about itself.

**Comment by theScottyJam** [comment]
Ok, I see, I guess the board does have access to the data required to know which cells are empty and which are not, even if the cell class isn't exposing it.
